# A sample Gemfile
source "http://rubygems.org"

if File.exists?('../backend/Gemfile') then
  eval File.read('../backend/Gemfile'), nil, '../backend/Gemfile'
end

if File.exists?('../frontend/Gemfile') then
  eval File.read('../frontend/Gemfile'), nil, '../frontend/Gemfile'
end

gem 'multi_json', '1.10.0'
gem 'rubyzip', '1.0.0'

group "test" do
	gem "selenium-webdriver", "2.45.0"
	gem "rspec", "~> 3.3.0"
  gem "parallel_tests", "~> 1.3.9"
end
